"""rename department

Revision ID: 374b8b14689a
Revises: 5a67a44e4384
Create Date: 2024-04-12 16:01:33.835762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374b8b14689a'
down_revision = '5a67a44e4384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
